/* eslint-disable */
/* global __dirname */
/* generated by unstuck-webpack */
const path = require('path')
const webpack = require('webpack');
const ExtractTextPlugin = require("extract-text-webpack-plugin");
const HtmlWebpackPlugin = require('html-webpack-plugin')
const CleanWebpackPlugin = require('clean-webpack-plugin');
const git = require('git-rev-sync');
const dir_js = path.resolve(__dirname, 'src/app');
const dir_css = path.resolve(__dirname, 'src/css');
const dir_build = path.resolve(__dirname, 'dist');

module.exports = {
  entry: {
    app : path.resolve(__dirname, 'src/index.js')
  },
  output: {
    path: dir_build,
    filename: 'bundle.[hash].js'
  },
  resolve: {
    modules: ['node_modules', dir_js],
  },
  stats: {
    colors: true,
    chunkModules: false
  },
  plugins: [
    new CleanWebpackPlugin(['dist']),
    new ExtractTextPlugin({
      filename: 'style.[hash].css',
      allChunks: true
    }),
    new HtmlWebpackPlugin({
      template: path.resolve(__dirname, 'src/index.html')
    }),
    new webpack.DefinePlugin({
      'process.env': {
        'NODE_ENV': JSON.stringify('production')
      },
      VERSION: JSON.stringify(git.short())
    }),
    new webpack.optimize.UglifyJsPlugin()
  ],
  
  module: {
    rules: [
      {
        loader: 'file-loader?name=assets/[name].[ext]',
        test: /\.png($|\?)|\.woff($|\?)|\.woff2($|\?)|\.ttf($|\?)|\.eot($|\?)|\.svg($|\?)/
      },
      {
        loader: 'babel-loader',
        test: /\.js($|\?)|\.jsx($|\?)/,
        exclude: /node_modules/,
        options: {
          presets : ['es2015', 'react']
        }
      },
      {
        test: /\.less$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
            'css-loader',
            {
              loader: 'postcss-loader',
              options: {
                plugins: function () {
                  return [
                    require('autoprefixer')
                  ];
                }
              }
            },
            'less-loader'
          ]
        })
      }
    ]
  }
}
