'use strict';

export const PLAYLIST_UPDATE = 'PLAYLIST_UPDATE';
export const CHAT_UPDATE = 'CHAT_UPDATE';
export const CHAT_START = 'CHAT_START';
export const CHAT_STOP = 'CHAT_STOP';
export const POSTAREA_SET_MESSAGE = 'POSTAREA_SET_MESSAGE';
export const POSTAREA_SET_FILE = 'POSTAREA_SET_FILE';
export const POSTAREA_SET_PREVIEW = 'POSTAREA_SET_PREVIEW';
export const POSTAREA_SET_PROCESSING = 'POSTAREA_SET_PROCESSING';
export const POSTAREA_RESET = 'POSTAREA_RESET';
export const SNACKBAR_OPEN = 'SNACKBAR_OPEN';
export const SNACKBAR_CLOSE = 'SNACKBAR_CLOSE';
export const SHOW_PREVIEW = 'SHOW_PREVIEW';
export const MOVE_PREVIEW = 'MOVE_PREVIEW';
export const HIDE_PREVIEW = 'HIDE_PREVIEW';
export const SET_ONLINE_COUNTER = 'SET_ONLINE_COUNTER';
